### PR TITLE
A few additional things I missed

### PR DESCRIPTION
**Pull request by EliteTK**
I forgot about some of the documentation/changelog updates.

I also missed something clippy complained about, but there was something else it wanted to fix so I rolled it into one commit (can always split if you want).

### CODE REVIEW

**Comment by EliteTK** [comment]
ah, you already added to the changelog, let me drop that change then

**Comment by EliteTK** [comment]
Okay, I dropped the changelog change from the commits. Feel free to drop anything else you don't like.

Also, thanks for this project. I really like it, makes it much more pleasant to use neovim with rust-analyser!

**Comment by EliteTK** [comment]
> i did the clippy thing and readme as well, sorry 😅
> 
> btw have you tried the neovim unix socket option? i'm running the proxy over a unix socket now from helix and it works great but i don't have a functional neovim setup to test the config example you pushed

Ah, okay, no worries. I can drop the rest or you can just cherry pick the one commit you want.

Yes, I am currently running that example:

image

**Comment by pr2502** [comment]
i've cherry-picked the neovim example and the second clippy fix to main. closing this. thank you:)

**Pull request closed without merging**
