### PR TITLE
warn if starting w default config

### LINKED ISSUE #12: Naively, ra-multiplex-server appears to fail to start when the config file is missing
If `~/.config/ra-multiplex/config.toml` does not exist, then `ra-multiplex-server` logs a warning. However, it doesn't indicate in the warning that everything is fine. This led me to believe `ra-multiplex-server` failed to start.

I recommend logging a message following the warning with something like "Proceeding with default configuration." Something like the following would be nice.

```
% ra-multiplex-server
[WARN ] cannot load config: cannot read config file `/.../.config/ra-multiplex/config.toml`

    Caused by:
        No such file or directory (os error 2)
[WARN ] Successfully started with default config
```

### PR DESCRIPTION
**Pull request by yaymukund**
Closes #12

### CODE REVIEW

**Comment by pr2502** [comment]
thanks for picking this up ^^
i'd just amend the original message to say "cannot load config file, continuing with defaults:"

**Comment by yaymukund** [comment]
You got it

**Comment by pr2502** [comment]
thanks!

**Comment by c6c7** [comment]
Thank you for the incredibly fast turnaround! Also, thank you for making this tool. This project has made my local experience with rust-analyzer much more stable.

**Pull request merged**
